# Generated by Django 2.2.2 on 2019-06-07 05:06

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accepted_TOS',
            field=models.BooleanField(validators=[users.validators.validate_accepted]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='accepted_privacy_policy',
            field=models.BooleanField(validators=[users.validators.validate_accepted]),
        ),
    ]
