# Generated by Django 3.0.7 on 2020-06-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed_0010_auto_20200602_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_not_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
    ]
