# Generated by Django 2.2.9 on 2020-01-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190609_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='accepted_TOS',
            new_name='accepted_terms_of_service',
        ),
    ]
