# Generated by Django 2.2.9 on 2020-03-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200130_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='accepted_privacy_policy',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='accepted_terms_of_service',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number_confirmed',
        ),
    ]
