# Generated by Django 2.2.2 on 2019-06-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190605_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='agree_tos_and_privacy',
            new_name='agree_TOS_and_privacy',
        ),
    ]
