# Generated by Django 2.2.2 on 2019-06-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agree_TOS_and_privacy',
            field=models.BooleanField(),
        ),
    ]
