# Generated by Django 3.0.6 on 2020-06-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='securitypolicy',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='termsofservice',
            name='effective_date',
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='document_identifier',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='document_identifier',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='document_identifier',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
